// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  location: dynamic(() => import("./Location")),
  richtext: dynamic(() => import("./Richtext")),
};
